# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=200)),
                ('intent_text', models.CharField(max_length=200)),
                ('intent_arg1', models.CharField(max_length=200)),
                ('intent_arg2', models.CharField(max_length=200)),
                ('intent_arg3', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name=b'date published')),
            ],
        )
    ]
